# title: "python_to_r"
# author: "Renee Liu"
# date: "January 28, 2019"


## References
[Tutorial](https://gist.github.com/primaryobjects/8038d345aae48ae48988906b0525d175)
[Repo for the functions used here](https://github.com/bmschmidt/wordVectors)
[Kaggle Demo](https://www.kaggle.com/rtatman/gender-bias-in-word-embeddings/notebook)
[Deep Learning R pretrained embeddings](https://jjallaire.github.io/deep-learning-with-r-notebooks/notebooks/6.1-using-word-embeddings.nb.html)

install.packages("devtools")
library(tidyverse)
library(data.table)
library(ggplot2)
library(devtools)
library(wordVectors)
library(httr)
library(tm)
devtools::install_github("bmschmidt/wordVectors")
# Helper function to train a word2vec model from file.txt or load an existing one from file.bin.

word2vec <- function(fileName) {
  if (grepl('.txt', fileName, fixed=T)) {
    # Convert test.txt to test.bin.
    binaryFileName <- gsub('.txt', '.bin', fileName, fixed=T)
  }
  else {
    binaryFileName <- paste0(fileName, '.bin')
  }
  
   # Train word2vec model.
  if (!file.exists(binaryFileName)) {
    # Lowercase and setup ngrams.
    prepFileName <- 'temp.prep'
    prep_word2vec(origin=fileName, destination=prepFileName, lowercase=T, bundle_ngrams=2)
    
    # Train word2vec model.
    model <- train_word2vec(prepFileName, binaryFileName, vectors=200, threads=4, window=12, iter=5, negative_samples=0)
    
    # Cleanup.
    unlink(prepFileName)
  }
  model}

# Read in data and remove stopwords
# Read text file.
doc <- readChar('data_sample.txt', file.info('data_sample.txt')$size)

# Remove stop-words.
stopwords_regex <- paste(stopwords('en'), collapse = '\\b|\\b')
stopwords_regex <- paste0('\\b', stopwords_regex, '\\b')
doc <- stringr::str_replace_all(doc, stopwords_regex, '')

# Write text file with stop-words removed.
cat(doc, file="data_sample_clean.txt",sep="\n",append=TRUE)

# Train word2vec model and explore what are the closest words to "he"
model <- word2vec('data_sample_clean.txt')
model %>% closest_to("he")

